package service

import (
	"testing"
	"time"

	"github.com/LutfiyaAinurrahmanP/sirekam-medis-pasien/internal/dto"
	"github.com/LutfiyaAinurrahmanP/sirekam-medis-pasien/internal/service/dashboard"
	"github.com/LutfiyaAinurrahmanP/sirekam-medis-pasien/tests/unit/mocks"
	"github.com/stretchr/testify/assert"
)

func setupTestDashboardService() (*mocks.MockDashboardRepository, dashboard.DashboardService) {
	mockRepo := new(mocks.MockDashboardRepository)
	service := dashboard.NewDashboardService(mockRepo)
	return mockRepo, service
}

func TestDashboardService_GetOverview_Success(t *testing.T) {
	mockRepo, service := setupTestDashboardService()
	query := &dto.DashboardOverviewQuery{Date: "2024-01-01"}
	expectedRes := mocks.NewTestDashboardOverviewResponse()

	mockRepo.On("GetOverview", "2024-01-01").Return(expectedRes, nil)

	res, err := service.GetOverview(query)

	assert.NoError(t, err)
	assert.NotNil(t, res)
	mockRepo.AssertExpectations(t)
}

func TestDashboardService_GetAdminDashboard_Success(t *testing.T) {
	mockRepo, service := setupTestDashboardService()
	query := &dto.DashboardPeriodQuery{Period: "custom", StartDate: "2024-01-01", EndDate: "2024-01-31"}
	expectedRes := mocks.NewTestDashboardAdminResponse()

	mockRepo.On("GetAdminDashboard", query, "2024-01-01", "2024-01-31").Return(expectedRes, nil)

	res, err := service.GetAdminDashboard(query)

	assert.NoError(t, err)
	assert.NotNil(t, res)
	mockRepo.AssertExpectations(t)
}

func TestDashboardService_GetDoctorDashboard_Success(t *testing.T) {
	mockRepo, service := setupTestDashboardService()
	query := &dto.DashboardDoctorQuery{Date: "2024-01-01"}
	expectedRes := mocks.NewTestDashboardDoctorResponse()

	mockRepo.On("GetDoctorDashboard", uint(1), "2024-01-01").Return(expectedRes, nil)

	res, err := service.GetDoctorDashboard(1, query)

	assert.NoError(t, err)
	assert.NotNil(t, res)
	mockRepo.AssertExpectations(t)
}

func TestDashboardService_GetReceptionistDashboard_Success(t *testing.T) {
	mockRepo, service := setupTestDashboardService()
	expectedRes := mocks.NewTestDashboardReceptionistResponse()

	// Today's date dynamically generated by service
	today := time.Now().Format("2006-01-02")
	mockRepo.On("GetReceptionistDashboard", today).Return(expectedRes, nil)

	res, err := service.GetReceptionistDashboard()

	assert.NoError(t, err)
	assert.NotNil(t, res)
	mockRepo.AssertExpectations(t)
}

func TestDashboardService_GetPatientDashboard_Success(t *testing.T) {
	mockRepo, service := setupTestDashboardService()
	expectedRes := mocks.NewTestDashboardPatientResponse()

	mockRepo.On("GetPatientDashboard", uint(1)).Return(expectedRes, nil)

	res, err := service.GetPatientDashboard(1)

	assert.NoError(t, err)
	assert.NotNil(t, res)
	mockRepo.AssertExpectations(t)
}

func TestDashboardService_GetAppointmentReport_Success(t *testing.T) {
	mockRepo, service := setupTestDashboardService()
	query := &dto.DashboardAppointmentReportQuery{Period: "custom", StartDate: "2024-01-01", EndDate: "2024-01-31"}
	expectedRes := mocks.NewTestDashboardAppointmentReportResponse()

	mockRepo.On("GetAppointmentReport", query, "2024-01-01", "2024-01-31").Return(expectedRes, nil)

	res, err := service.GetAppointmentReport(query)

	assert.NoError(t, err)
	assert.NotNil(t, res)
	mockRepo.AssertExpectations(t)
}

func TestDashboardService_GetRevenueReport_Success(t *testing.T) {
	mockRepo, service := setupTestDashboardService()
	query := &dto.DashboardRevenueReportQuery{Period: "custom", StartDate: "2024-01-01", EndDate: "2024-01-31"}
	expectedRes := mocks.NewTestDashboardRevenueReportResponse()

	mockRepo.On("GetRevenueReport", query, "2024-01-01", "2024-01-31").Return(expectedRes, nil)

	res, err := service.GetRevenueReport(query)

	assert.NoError(t, err)
	assert.NotNil(t, res)
	mockRepo.AssertExpectations(t)
}

func TestDashboardService_GetPatientReport_Success(t *testing.T) {
	mockRepo, service := setupTestDashboardService()
	query := &dto.DashboardPatientReportQuery{Period: "custom", StartDate: "2024-01-01", EndDate: "2024-01-31"}
	expectedRes := mocks.NewTestDashboardPatientReportResponse()

	mockRepo.On("GetPatientReport", query, "2024-01-01", "2024-01-31").Return(expectedRes, nil)

	res, err := service.GetPatientReport(query)

	assert.NoError(t, err)
	assert.NotNil(t, res)
	mockRepo.AssertExpectations(t)
}
